classdef filter_method
       %Summary of FILTER_METHOD:
    %   The FILTER_METHOD class controls the filter_method superclass in NM2 framework.
    %
    %   FILTER_METHOD properties:
    %   parameters - ...
    %   parameters_descriptor - ...
    %   model - ...
    %   reports - ...
    
    %   FILTER_METHOD revision history:
    %   Date of creation: 18 of July 2016
    %   First used in: NM2.0 beta (Helena)
    %   Creator: Carlos Cabral
    properties
        parameters; %FORMAT: struct; Description : Structure 
        parameter_descriptor;%FORMAT: string; DESCRIPTION: String describing the paramters used for the model
        model;  %FORMAT: struct; DESCRIPTION : Structure with the model generated by the filter_method. In this case, a structure with 2 fields:weight_vector and cut_off_struct.
        reports; %FORMAT: report class object ; DESCRIPTION: Report class
        %object that describes the status and incidences in the model
        %estimation/application process
    end
    
    methods (Abstract)
       weight_estimator(obj,data)
       %Estimate the weight map based on the object and the data.
    end
end