function res =confusion_matrix(r)
%CONFUSION_MATRIX (RESULTS class) determines the confusion matrices of a set
% of classification experiments from an array of RESULTS classs objects.
% 
%   CONF=CONFUSION_MATRIX (R) returns the confusion matrices of the 
%   classification experiment that generated the RESULTS array (R).
%
%   R (RESULTS class array) must have been generated by a classification 
%   experiment, for all the other evaluation processes (ranking and 
%   regression) is not possible to compute a confusion matrix.
%
%   RES is a cell array of the same size as R, each position of RES
%   represents the confusion matrix of the correspondent component of R 
%   (2D double array), evaluation processes that do not correspond to 
%   classification experiments are treated as NaN. 


%   RES=CONFUSION_MATRIX (R)
%   See also RESULTS, EVALUATION, ENSEMBLE_LEARNING

%   CONFUSION_MATRIX (RESULTS class)  revision history:
%   Date of creation: 05 November 2014 beta (Helena)
%   Creator: Carlos Cabral
res=cell(numel(r),1);
for i=1:numel(r)
    aux=r(i);
    %% Overture: Getting the number of classes in the problem for unimodal labels for multimodal labels further development must be done... an idea might be using the combination of all the possible labels
    if  any(strcmp(aux.evaluation_type,{'binary_classification','multiclass_classification','semisupervised_learning','one_class_modeling'}))
        aux_target_values=aux.target_values;
        aux_predictions=aux.hard_labels;
        labels=aux.classes;
        %% Act: Computing the Confusion Matrix
        confusion=zeros(numel(labels));
        for j=1:numel(labels)
            
            aux_pos=cell2mat(aux_target_values)==labels(j);
            
            aux_class_target=aux_predictions(aux_pos);
            for l=1:numel(labels)
                
                confusion(j,l)=sum(cell2mat(aux_class_target)==labels(l));
                
            end
        end
        res{i}=confusion;
    else
        res{i}=NaN;
        warning('confusion_matrix:IncompatibilityError',['CONFUSION_MATRIX (RESULTS class) is undifined for empty objects and ' aux.evaluation_type ' results.'])
    end
end
%% Finale: No Finale the sky is the limit
end